/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * API de Gestão de Portfólio
 * Contrato de API para o CMS e exibição da Landing Page do Portfólio (Modulo Portfolio)
 * OpenAPI spec version: 1.0.0
 */

export interface ProjetoRequest {
  titulo: string;
  descricao?: string;
  urlCapa?: string;
  linkProducao?: string;
  linkRepositorio?: string;
  dataDesenvolvimento?: string;
  tecnologiaIds?: string[];
}
