/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as AdminProjectsNewRouteImport } from './routes/admin.projects.new'
import { Route as AdminProjectsIdEditRouteImport } from './routes/admin.projects.$id.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjectsNewRoute = AdminProjectsNewRouteImport.update({
  id: '/admin/projects/new',
  path: '/admin/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjectsIdEditRoute = AdminProjectsIdEditRouteImport.update({
  id: '/admin/projects/$id/edit',
  path: '/admin/projects/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/projects/new': typeof AdminProjectsNewRoute
  '/admin/projects/$id/edit': typeof AdminProjectsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/projects/new': typeof AdminProjectsNewRoute
  '/admin/projects/$id/edit': typeof AdminProjectsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/projects/new': typeof AdminProjectsNewRoute
  '/admin/projects/$id/edit': typeof AdminProjectsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/projects/$slug'
    | '/admin/'
    | '/admin/projects/new'
    | '/admin/projects/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/projects/$slug'
    | '/admin'
    | '/admin/projects/new'
    | '/admin/projects/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/projects/$slug'
    | '/admin/'
    | '/admin/projects/new'
    | '/admin/projects/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminProjectsNewRoute: typeof AdminProjectsNewRoute
  AdminProjectsIdEditRoute: typeof AdminProjectsIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projects/new': {
      id: '/admin/projects/new'
      path: '/admin/projects/new'
      fullPath: '/admin/projects/new'
      preLoaderRoute: typeof AdminProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projects/$id/edit': {
      id: '/admin/projects/$id/edit'
      path: '/admin/projects/$id/edit'
      fullPath: '/admin/projects/$id/edit'
      preLoaderRoute: typeof AdminProjectsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminProjectsNewRoute: AdminProjectsNewRoute,
  AdminProjectsIdEditRoute: AdminProjectsIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
